package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"strings"
	"sync"
)

func init() {
	Register(Spec{
		Kind:  KindBox,
		Label: "Box",
		Description: "A Box account. Sign in and SAND keeps its parts in one folder; Box hands " +
			"out a fresh refresh token on every renewal and SAND stores it as it goes.",
		DocsURL: "https://developer.box.com/reference/",
		Order:   13,
		Fields: []FieldSpec{
			{Key: "client_id", Label: "Client ID", Required: true, Advanced: true},
			{Key: "client_secret", Label: "Client secret", Secret: true, Required: true, Advanced: true},
			{Key: "refresh_token", Label: "Refresh token", Secret: true, Required: true, Advanced: true},
			{
				Key:     "folder",
				Label:   "Folder",
				Default: "sand",
				Help:    "Folder in the account root to store shards in. Created if missing.",
			},
		},
		OAuth: &OAuthSpec{
			SignInLabel:       "Continue with Box",
			AuthURL:           "https://account.box.com/api/oauth2/authorize",
			TokenURL:          boxTokenURL,
			SecretRequired:    true,
			ClientIDField:     "client_id",
			ClientSecretField: "client_secret",
			RefreshTokenField: "refresh_token",
			ClientIDEnv:       "SAND_BOX_CLIENT_ID",
			ClientSecretEnv:   "SAND_BOX_CLIENT_SECRET",
			ConsoleURL:        "https://app.box.com/developers/console",
			ConsoleHelp: "Create a Custom App with standard OAuth 2.0 (User Authentication), tick " +
				"“Write all files and folders”, and add the redirect URI below.",
		},
	}, newBoxProvider)
}

// boxAPI and boxUpload are Box's two hosts — metadata on one, bytes on the
// other. Variables rather than constants so the tests can point the backend at
// a stub.
var (
	boxAPI    = "https://api.box.com/2.0"
	boxUpload = "https://upload.box.com/api/2.0"
)

const (
	boxTokenURL = "https://api.box.com/oauth2/token"
	boxRoot     = "0"
)

// boxProvider stores each shard as a file in a single Box folder. Box has no
// path addressing — everything is an item ID — so the object key becomes a
// flat filename and the ID it maps to is cached.
type boxProvider struct {
	oauthBase
	folderName string

	mu       sync.Mutex
	folderID string
	idCache  map[string]string
}

func newBoxProvider(cfg Config) (Provider, error) {
	name := strings.Trim(strings.TrimSpace(cfg.Option("folder")), "/")
	return &boxProvider{
		oauthBase: oauthBase{
			base: base{cfg: cfg},
			tokens: &tokenSource{
				tokenURL:     boxTokenURL,
				clientID:     cfg.Option("client_id"),
				clientSecret: cfg.Option("client_secret"),
				refreshToken: strings.TrimSpace(cfg.Option("refresh_token")),
			},
			refreshField: "refresh_token",
		},
		folderName: name,
		idCache:    map[string]string{},
	}, nil
}

// boxName flattens an object key into a single filename, since every shard
// lives in the same folder.
func boxName(key string) string {
	return strings.ReplaceAll(strings.Trim(key, "/"), "/", "_")
}

// keyFromBoxName undoes boxName. Shard keys are generated by SAND and contain
// no underscores of their own, so the round trip is exact.
func keyFromBoxName(name string) string {
	return strings.ReplaceAll(name, "_", "/")
}

func (p *boxProvider) do(ctx context.Context, req *http.Request) (*http.Response, error) {
	if err := p.tokens.authorize(ctx, req); err != nil {
		return nil, err
	}
	return httpClient.Do(req)
}

// getJSON fetches a Box resource into out, reporting ErrNotFound for a 404.
func (p *boxProvider) getJSON(ctx context.Context, op, rawURL string, out any) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return err
	}
	resp, err := p.do(ctx, req)
	if err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}
	defer drainAndClose(resp)
	if resp.StatusCode == http.StatusNotFound {
		return ErrNotFound
	}
	if !isSuccess(resp.StatusCode) {
		return httpError(op, resp)
	}
	body, err := readAllBody(resp)
	if err != nil {
		return err
	}
	if out == nil {
		return nil
	}
	if err := json.Unmarshal(body, out); err != nil {
		return fmt.Errorf("%s: parsing response: %w", op, err)
	}
	return nil
}

// boxItem is the subset of Box's item resource SAND reads.
type boxItem struct {
	Type string `json:"type"`
	ID   string `json:"id"`
	Name string `json:"name"`
	Size int64  `json:"size"`
}

// folder resolves — creating if necessary — the folder shards live in.
func (p *boxProvider) folder(ctx context.Context) (string, error) {
	if p.folderName == "" {
		return boxRoot, nil
	}

	p.mu.Lock()
	cached := p.folderID
	p.mu.Unlock()
	if cached != "" {
		return cached, nil
	}

	items, err := p.listFolder(ctx, boxRoot)
	if err != nil {
		return "", err
	}
	for _, item := range items {
		if item.Type == "folder" && item.Name == p.folderName {
			p.mu.Lock()
			p.folderID = item.ID
			p.mu.Unlock()
			return item.ID, nil
		}
	}

	body, err := json.Marshal(map[string]any{
		"name":   p.folderName,
		"parent": map[string]string{"id": boxRoot},
	})
	if err != nil {
		return "", err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, boxAPI+"/folders", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := p.do(ctx, req)
	if err != nil {
		return "", fmt.Errorf("box create folder: %w", err)
	}
	defer drainAndClose(resp)

	// A 409 means someone — probably a parallel upload of the same file's
	// other parts — created it first.
	if resp.StatusCode == http.StatusConflict {
		return p.folderByConflict(resp)
	}
	if !isSuccess(resp.StatusCode) {
		return "", httpError("box create folder", resp)
	}

	raw, err := readAllBody(resp)
	if err != nil {
		return "", err
	}
	var created boxItem
	if err := json.Unmarshal(raw, &created); err != nil {
		return "", fmt.Errorf("box create folder: parsing response: %w", err)
	}
	p.mu.Lock()
	p.folderID = created.ID
	p.mu.Unlock()
	return created.ID, nil
}

// folderByConflict digs the existing folder's ID out of a 409 response.
func (p *boxProvider) folderByConflict(resp *http.Response) (string, error) {
	raw, err := readAllBody(resp)
	if err != nil {
		return "", err
	}
	var conflict struct {
		ContextInfo struct {
			Conflicts []boxItem `json:"conflicts"`
		} `json:"context_info"`
	}
	if err := json.Unmarshal(raw, &conflict); err != nil || len(conflict.ContextInfo.Conflicts) == 0 {
		return "", fmt.Errorf("box create folder: %s already exists but its ID was not reported", p.folderName)
	}
	id := conflict.ContextInfo.Conflicts[0].ID
	p.mu.Lock()
	p.folderID = id
	p.mu.Unlock()
	return id, nil
}

// listFolder returns every item in a folder, following Box's offset paging.
func (p *boxProvider) listFolder(ctx context.Context, folderID string) ([]boxItem, error) {
	var out []boxItem
	offset := 0

	for {
		var page struct {
			Entries    []boxItem `json:"entries"`
			TotalCount int       `json:"total_count"`
		}
		addr := fmt.Sprintf("%s/folders/%s/items?fields=name,size,type&limit=1000&offset=%d",
			boxAPI, url.PathEscape(folderID), offset)
		if err := p.getJSON(ctx, "box list", addr, &page); err != nil {
			return nil, err
		}
		out = append(out, page.Entries...)

		offset += len(page.Entries)
		if len(page.Entries) == 0 || offset >= page.TotalCount {
			return out, nil
		}
	}
}

// fileIDFor resolves an object key to a Box file ID, filling the cache from a
// folder listing on a miss.
func (p *boxProvider) fileIDFor(ctx context.Context, key string) (string, error) {
	name := boxName(key)

	p.mu.Lock()
	cached, ok := p.idCache[name]
	p.mu.Unlock()
	if ok {
		return cached, nil
	}

	folderID, err := p.folder(ctx)
	if err != nil {
		return "", err
	}
	items, err := p.listFolder(ctx, folderID)
	if err != nil {
		return "", err
	}

	p.mu.Lock()
	for _, item := range items {
		if item.Type == "file" {
			p.idCache[item.Name] = item.ID
		}
	}
	id, found := p.idCache[name]
	p.mu.Unlock()

	if !found {
		return "", ErrNotFound
	}
	return id, nil
}

func (p *boxProvider) forget(key string) {
	p.mu.Lock()
	delete(p.idCache, boxName(key))
	p.mu.Unlock()
}

func (p *boxProvider) remember(key, id string) {
	p.mu.Lock()
	p.idCache[boxName(key)] = id
	p.mu.Unlock()
}

func (p *boxProvider) Put(ctx context.Context, key string, data []byte) error {
	folderID, err := p.folder(ctx)
	if err != nil {
		return err
	}

	// Uploading over an existing name is a new version of that file, which is
	// a different endpoint from creating one.
	existing, err := p.fileIDFor(ctx, key)
	if err != nil && err != ErrNotFound {
		return err
	}

	attributes := map[string]any{"name": boxName(key)}
	endpoint := boxUpload + "/files/content"
	if existing != "" {
		endpoint = boxUpload + "/files/" + url.PathEscape(existing) + "/content"
	} else {
		attributes["parent"] = map[string]string{"id": folderID}
	}

	uploaded, err := p.upload(ctx, endpoint, attributes, data)
	if err != nil {
		return err
	}
	if uploaded != "" {
		p.remember(key, uploaded)
	}
	return nil
}

// upload posts a shard as the multipart body Box's upload endpoints want, and
// returns the file ID it landed under.
func (p *boxProvider) upload(ctx context.Context, endpoint string, attributes map[string]any, data []byte) (string, error) {
	attrJSON, err := json.Marshal(attributes)
	if err != nil {
		return "", err
	}

	var body bytes.Buffer
	mw := multipart.NewWriter(&body)
	if err := mw.WriteField("attributes", string(attrJSON)); err != nil {
		return "", err
	}
	part, err := mw.CreateFormFile("file", fmt.Sprint(attributes["name"]))
	if err != nil {
		return "", err
	}
	if _, err := part.Write(data); err != nil {
		return "", err
	}
	if err := mw.Close(); err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body.Bytes()))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", mw.FormDataContentType())
	req.ContentLength = int64(body.Len())

	resp, err := p.do(ctx, req)
	if err != nil {
		return "", fmt.Errorf("box upload: %w", err)
	}
	defer drainAndClose(resp)
	if !isSuccess(resp.StatusCode) {
		return "", httpError("box upload", resp)
	}

	raw, err := readAllBody(resp)
	if err != nil {
		return "", err
	}
	var created struct {
		Entries []boxItem `json:"entries"`
	}
	if err := json.Unmarshal(raw, &created); err != nil || len(created.Entries) == 0 {
		return "", nil
	}
	return created.Entries[0].ID, nil
}

func (p *boxProvider) Get(ctx context.Context, key string) ([]byte, error) {
	id, err := p.fileIDFor(ctx, key)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		boxAPI+"/files/"+url.PathEscape(id)+"/content", nil)
	if err != nil {
		return nil, err
	}
	resp, err := p.do(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("box download: %w", err)
	}
	defer drainAndClose(resp)
	if resp.StatusCode == http.StatusNotFound {
		p.forget(key)
		return nil, ErrNotFound
	}
	if !isSuccess(resp.StatusCode) {
		return nil, httpError("box download", resp)
	}
	return readAllBody(resp)
}

func (p *boxProvider) Stat(ctx context.Context, key string) (ObjectInfo, error) {
	id, err := p.fileIDFor(ctx, key)
	if err != nil {
		return ObjectInfo{}, err
	}

	var item boxItem
	err = p.getJSON(ctx, "box stat",
		boxAPI+"/files/"+url.PathEscape(id)+"?fields=name,size", &item)
	if err == ErrNotFound {
		p.forget(key)
		return ObjectInfo{}, ErrNotFound
	}
	if err != nil {
		return ObjectInfo{}, err
	}
	return ObjectInfo{Key: key, Size: item.Size}, nil
}

func (p *boxProvider) Delete(ctx context.Context, key string) error {
	id, err := p.fileIDFor(ctx, key)
	if err == ErrNotFound {
		return nil
	}
	if err != nil {
		return err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodDelete,
		boxAPI+"/files/"+url.PathEscape(id), nil)
	if err != nil {
		return err
	}
	resp, err := p.do(ctx, req)
	if err != nil {
		return fmt.Errorf("box delete: %w", err)
	}
	defer drainAndClose(resp)
	p.forget(key)
	if resp.StatusCode == http.StatusNotFound {
		return nil
	}
	if !isSuccess(resp.StatusCode) {
		return httpError("box delete", resp)
	}
	return nil
}

func (p *boxProvider) List(ctx context.Context, prefix string) ([]ObjectInfo, error) {
	folderID, err := p.folder(ctx)
	if err != nil {
		return nil, err
	}
	items, err := p.listFolder(ctx, folderID)
	if err != nil {
		return nil, err
	}

	var out []ObjectInfo
	for _, item := range items {
		if item.Type != "file" {
			continue
		}
		key := keyFromBoxName(item.Name)
		if !strings.HasPrefix(key, prefix) {
			continue
		}
		out = append(out, ObjectInfo{Key: key, Size: item.Size})
	}
	return out, nil
}

func (p *boxProvider) Ping(ctx context.Context) error {
	if err := p.getJSON(ctx, "box check", boxAPI+"/users/me?fields=id", nil); err != nil {
		return fmt.Errorf("cannot reach Box: %w", err)
	}
	return nil
}

// Account reports the signed-in Box account, used to label the connection.
func (p *boxProvider) Account(ctx context.Context) (string, error) {
	var me struct {
		Login string `json:"login"`
		Name  string `json:"name"`
	}
	if err := p.getJSON(ctx, "box account", boxAPI+"/users/me?fields=login,name", &me); err != nil {
		return "", err
	}
	if me.Login != "" {
		return me.Login, nil
	}
	return me.Name, nil
}

func (p *boxProvider) Usage(ctx context.Context) (Usage, error) {
	var me struct {
		SpaceAmount int64 `json:"space_amount"`
		SpaceUsed   int64 `json:"space_used"`
	}
	err := p.getJSON(ctx, "box usage",
		boxAPI+"/users/me?fields=space_amount,space_used", &me)
	if err != nil {
		return Usage{}, err
	}
	return Usage{Used: me.SpaceUsed, Total: me.SpaceAmount}, nil
}
